"""Users fixessss

Revision ID: 00a6daf07cad
Revises: ea7bec1f99d1
Create Date: 2024-10-30 19:11:34.682969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a6daf07cad'
down_revision: Union[str, None] = 'ea7bec1f99d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    op.alter_column('Users', 'last_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'last_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    # ### end Alembic commands ###
