"""Users change password to bytes x2

Revision ID: 058353c625ed
Revises: b74051f40c9c
Create Date: 2024-10-31 18:43:08.530113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058353c625ed'
down_revision: Union[str, None] = 'b74051f40c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.LargeBinary(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###
