"""upd x2

Revision ID: 099922825df4
Revises: 1c602e919dd6
Create Date: 2024-11-09 08:06:18.984892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099922825df4'
down_revision: Union[str, None] = '1c602e919dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MatchMember')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MatchMember',
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['Match.id'], name='MatchMember_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], name='MatchMember_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', name='MatchMember_pkey')
    )
    # ### end Alembic commands ###
