"""Wtf x2

Revision ID: 0dbb99c94030
Revises: 72a53479dd2d
Create Date: 2024-11-09 10:08:13.584508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dbb99c94030'
down_revision: Union[str, None] = '72a53479dd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MatchMember')
    op.drop_table('Match')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MatchMember',
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['Match.id'], name='MatchMember_match_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], name='MatchMember_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'team_id', name='MatchMember_pkey')
    )
    op.create_table('Match',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_winner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_winner_id'], ['Team.id'], name='Match_team_winner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Match_pkey')
    )
    # ### end Alembic commands ###
