"""TeamMembersORM added foreign key for member_id

Revision ID: 12ab6ee892fe
Revises: 7f3459c081ce
Create Date: 2024-11-03 17:16:43.141381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ab6ee892fe'
down_revision: Union[str, None] = '7f3459c081ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'TeamsMembers', 'Users', ['member_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TeamsMembers', type_='foreignkey')
    # ### end Alembic commands ###
