"""upd x3

Revision ID: 29556fe4e202
Revises: 099922825df4
Create Date: 2024-11-09 08:06:37.265288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29556fe4e202'
down_revision: Union[str, None] = '099922825df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MatchMember',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['Match.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('match_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MatchMember')
    # ### end Alembic commands ###
