"""Add Matches

Revision ID: 359600991585
Revises: df5bff887889
Create Date: 2024-11-09 06:14:52.009782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359600991585'
down_revision: Union[str, None] = 'df5bff887889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_winner_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_winner_id'], ['Team.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MatchMember',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['Match.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MatchMember')
    op.drop_table('Match')
    # ### end Alembic commands ###
