"""Add Matches and etc after pizdec

Revision ID: 4db5c5b6c5da
Revises: 4e7ee9dca801
Create Date: 2024-11-09 09:50:18.532911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db5c5b6c5da'
down_revision: Union[str, None] = '4e7ee9dca801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('Match', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'Match', 'Team', ['team_winner_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_column('Match', 'ended_at')
    op.drop_column('Match', 'started_at')
    # ### end Alembic commands ###
