"""Match.status nullable false

Revision ID: 4e7ee9dca801
Revises: bf4cde2a816c
Create Date: 2024-11-09 09:37:54.681730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7ee9dca801'
down_revision: Union[str, None] = 'bf4cde2a816c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Match', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
