"""Initial x6

Revision ID: 632b2e3dbcac
Revises: 67a3e95b658c
Create Date: 2024-10-27 17:27:46.844294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632b2e3dbcac'
down_revision: Union[str, None] = '67a3e95b658c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Teams_pkey')
    )
    # ### end Alembic commands ###
