"""Wtf

Revision ID: 65d21b8f3102
Revises: 4db5c5b6c5da
Create Date: 2024-11-09 10:02:29.526529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d21b8f3102'
down_revision: Union[str, None] = '4db5c5b6c5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('id_', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Match', 'id_')
    # ### end Alembic commands ###
