"""Rename Match.finished_at

Revision ID: 6cf52fc9d2ae
Revises: 4cc82e06ae89
Create Date: 2024-11-09 14:23:47.393135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cf52fc9d2ae'
down_revision: Union[str, None] = '4cc82e06ae89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.drop_column('Match', 'ended_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Match', 'finished_at')
    # ### end Alembic commands ###
