"""Match.id set to primary key

Revision ID: 72a53479dd2d
Revises: 65d21b8f3102
Create Date: 2024-11-09 10:02:51.933261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a53479dd2d'
down_revision: Union[str, None] = '65d21b8f3102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Match', 'id_')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('id_', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
