"""TeamMembersORM role type swich to Enum

Revision ID: 7f3459c081ce
Revises: 058353c625ed
Create Date: 2024-11-03 17:02:27.805033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3459c081ce'
down_revision: Union[str, None] = '058353c625ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TeamsMembers_team_id_fkey', 'TeamsMembers', type_='foreignkey')
    op.create_foreign_key(None, 'TeamsMembers', 'Teams', ['team_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TeamsMembers', type_='foreignkey')
    op.create_foreign_key('TeamsMembers_team_id_fkey', 'TeamsMembers', 'Teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
