"""Users fixes add nullable true

Revision ID: 8c67671a7243
Revises: 00a6daf07cad
Create Date: 2024-10-30 19:14:15.619613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c67671a7243'
down_revision: Union[str, None] = '00a6daf07cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    op.alter_column('Users', 'last_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'last_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    op.alter_column('Users', 'first_name',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    # ### end Alembic commands ###
