"""Some fixes

Revision ID: 9091df2993b1
Revises: ccccacb80bf8
Create Date: 2024-10-30 18:50:35.039051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9091df2993b1'
down_revision: Union[str, None] = 'ccccacb80bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Teams', 'name',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=48),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Teams', 'name',
               existing_type=sa.String(length=48),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###
