"""Users change password to bytes

Revision ID: b74051f40c9c
Revises: 8c67671a7243
Create Date: 2024-10-31 18:42:58.887106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74051f40c9c'
down_revision: Union[str, None] = '8c67671a7243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
