"""najor changes

Revision ID: be54876293d1
Revises: 12ab6ee892fe
Create Date: 2024-11-08 17:27:37.158725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be54876293d1'
down_revision: Union[str, None] = '12ab6ee892fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('first_name', sa.String(length=48), nullable=True),
    sa.Column('last_name', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('password', sa.LargeBinary(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('TeamMember',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['User.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('team_id', 'member_id')
    )
    op.drop_table('TeamsMembers')
    op.drop_table('Users')
    op.drop_table('Teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teams',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Teams_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=48), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=48), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=48), autoincrement=False, nullable=True),
    sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Users_pkey'),
    sa.UniqueConstraint('name', name='Users_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('TeamsMembers',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['Users.id'], name='TeamsMembers_member_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['Teams.id'], name='TeamsMembers_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'member_id', name='TeamsMembers_pkey')
    )
    op.drop_table('TeamMember')
    op.drop_table('User')
    op.drop_table('Team')
    op.drop_table('Admin')
    # ### end Alembic commands ###
