"""Update MatchORM

Revision ID: bf4cde2a816c
Revises: 29556fe4e202
Create Date: 2024-11-09 09:37:23.041777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4cde2a816c'
down_revision: Union[str, None] = '29556fe4e202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Match', 'status')
    # ### end Alembic commands ###
