"""Add match type

Revision ID: fee3c51c5cd4
Revises: 359600991585
Create Date: 2024-11-09 06:31:35.011754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee3c51c5cd4'
down_revision: Union[str, None] = '359600991585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Match', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Match', 'type')
    # ### end Alembic commands ###
